# Generated by Django 3.2.5 on 2021-11-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_disease_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreId', models.CharField(max_length=200)),
                ('Medname', models.CharField(max_length=200)),
                ('Medtype', models.CharField(max_length=200, unique=True)),
                ('Dname', models.CharField(max_length=200)),
                ('Symptoms', models.CharField(max_length=200)),
                ('MedQty', models.CharField(max_length=200, unique=True)),
                ('MedPrice', models.CharField(max_length=200, unique=True)),
                ('Date', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
