# Generated by Django 3.2.5 on 2021-11-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_medicine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_table',
            name='Date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine_table',
            name='MedPrice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine_table',
            name='MedQty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine_table',
            name='Medtype',
            field=models.CharField(max_length=200),
        ),
    ]
