# Generated by Django 3.2.5 on 2021-11-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211108_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Phone', models.CharField(max_length=200, unique=True)),
                ('Bgroup', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Active', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
