# Generated by Django 3.2.5 on 2021-11-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_reg_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_public',
            name='Bgroup',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reg_public',
            name='Email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reg_public',
            name='Phone',
            field=models.CharField(max_length=200),
        ),
    ]
