# Generated by Django 3.2.5 on 2021-11-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20211110_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usid', models.CharField(max_length=200)),
                ('Stid', models.CharField(max_length=200)),
                ('Medname', models.CharField(max_length=200)),
                ('Count', models.CharField(max_length=200)),
                ('Medprice', models.CharField(max_length=200)),
                ('Total', models.CharField(max_length=200)),
            ],
        ),
    ]
