# Generated by Django 3.2.5 on 2021-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usid', models.CharField(max_length=200)),
                ('Stid', models.CharField(max_length=200)),
                ('Medname', models.CharField(max_length=200)),
                ('Qty', models.CharField(max_length=200)),
                ('Medprice', models.CharField(max_length=200)),
                ('Total', models.CharField(max_length=200)),
                ('Imgid', models.CharField(max_length=200)),
                ('Apprsts', models.CharField(max_length=200)),
                ('Delivert_sts', models.CharField(max_length=200)),
            ],
        ),
    ]
