# Generated by Django 3.2.5 on 2021-11-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='Apprsts',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Delivert_sts',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
