# Generated by Django 3.2.5 on 2021-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20211112_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='Paytype',
            field=models.CharField(default='', max_length=200),
        ),
    ]
