# Generated by Django 3.2.5 on 2021-11-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_order_table_paytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='Date',
            field=models.CharField(default='12/11/2021', max_length=200),
        ),
    ]
