# Generated by Django 3.2.5 on 2021-11-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_reg_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_donor',
            name='Active',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
