# Generated by Django 3.2.5 on 2021-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_reg_donor_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.CharField(max_length=200)),
                ('Rid', models.CharField(max_length=200)),
                ('Dname', models.CharField(max_length=200)),
                ('Dplace', models.CharField(max_length=200)),
                ('Rname', models.CharField(max_length=200)),
                ('Bldgrp', models.CharField(max_length=200)),
                ('Reqsts', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
