# Generated by Django 3.2.5 on 2021-11-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_donation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_table',
            name='Rplc',
            field=models.CharField(default='Ernakulam', max_length=200),
        ),
    ]
