# Generated by Django 3.2 on 2022-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_donation_table_rplc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ame', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Phone', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Job_sec', models.CharField(max_length=200)),
                ('B_sal', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart_table',
        ),
        migrations.DeleteModel(
            name='Disease_table',
        ),
        migrations.DeleteModel(
            name='Donation_table',
        ),
        migrations.DeleteModel(
            name='Med_login',
        ),
        migrations.DeleteModel(
            name='Medicine_table',
        ),
        migrations.DeleteModel(
            name='Order_table',
        ),
        migrations.DeleteModel(
            name='Reg_donor',
        ),
        migrations.DeleteModel(
            name='Reg_public',
        ),
    ]
