# Generated by Django 3.2 on 2022-02-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_reg_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_employee',
            old_name='Emp_ame',
            new_name='Emp_name',
        ),
    ]
