# Generated by Django 3.2 on 2022-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_rename_emp_ame_reg_employee_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usernm', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Punchin', models.CharField(max_length=200)),
                ('Punchout', models.CharField(max_length=200)),
            ],
        ),
    ]
