# Generated by Django 3.2 on 2022-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_attendance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_table',
            name='hours',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance_table',
            name='Punchout',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
