# Generated by Django 3.2 on 2022-02-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20220218_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usernm', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Reason', models.CharField(max_length=200)),
                ('Status', models.CharField(default='Not approved', max_length=200)),
            ],
        ),
    ]
