# Generated by Django 3.2 on 2022-02-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_salary_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_table',
            name='Date',
        ),
    ]
