# Generated by Django 3.2 on 2022-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_attendance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
            ],
        ),
    ]
