# Generated by Django 3.2 on 2023-05-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_notify_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Stime', models.CharField(default='0', max_length=200)),
                ('Etime', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
