# Generated by Django 3.2 on 2023-05-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_subject_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_table',
            name='Subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
